---
description: ""
enabled: true
runner_type: "python-script"
entry_point: ipa_action.py
name: config_mod
pack: freeipa
parameters:
############################################################################
# begin unique params for this action
  addattr:
    type: array
    items:
      type: string
  all:
    type: boolean
    required: true
    default: False
  ca_renewal_master_server:
    type: string
  delattr:
    type: array
    items:
      type: string
  ipaconfigstring:
    type: array
    enum:
      - AllowNThash
      - KDC:Disable Last Success
      - KDC:Disable Lockout
      - KDC:Disable Default Preauth for SPNs

    items:
      type: string
  ipadefaultemaildomain:
    type: string
  ipadefaultloginshell:
    type: string
  ipadefaultprimarygroup:
    type: string
  ipadomainresolutionorder:
    type: string
  ipagroupobjectclasses:
    type: array
    items:
      type: string
  ipagroupsearchfields:
    type: string
  ipahomesrootdir:
    type: string
  ipakrbauthzdata:
    type: array
    enum:
      - MS-PAC
      - PAD
      - nfs:NONE

    items:
      type: string
  ipamaxusernamelength:
    type: integer
  ipamigrationenabled:
    type: boolean
  ipapwdexpadvnotify:
    type: integer
  ipasearchrecordslimit:
    type: integer
  ipasearchtimelimit:
    type: integer
  ipaselinuxusermapdefault:
    type: string
  ipaselinuxusermaporder:
    type: string
  ipauserauthtype:
    type: array
    enum:
      - password
      - radius
      - otp
      - disabled

    items:
      type: string
  ipauserobjectclasses:
    type: array
    items:
      type: string
  ipausersearchfields:
    type: string
  raw:
    type: boolean
    required: true
    default: False
  rights:
    type: boolean
    required: true
    default: False
  setattr:
    type: array
    items:
      type: string
  version:
    type: string
############################################################################
# begin static invocation params
  method:
    type: string
    description: "Name of IPA command to be executed."
    default: "config_mod"
    immutable: true
############################################################################
# begin connection params
  session:
    type: string
    description: "Login session cookie. If empty then username/password will be used to login prior to running this operation"
    required: false
    secret: true
  connection:
    type: string
    description: "Name of <connection> from this pack's configuration that specifies how to connect to a IPA server."
    required: false
  server:
    type: string
    description: "Optional override of the IPA server in <connection> (required if <connection> is not specified)."
    required: false
  username:
    type: string
    description: "Optional override of the IPA username in <connection> (example: username@domain.tld) (required if <connection> is not specified)."
    required: false
  password:
    type: string
    description: "Optional override of the IPA password in <connection>. (required if <connection> is not specified)"
    required: false
    secret: true
  verify_ssl:
    type: boolean
    description: "Verify SSL certificates on the server"
    required: false